
(function(root,factory){if(typeof exports==='object'){factory(exports);}else if(typeof define==='function'&&define.amd){define(['exports'],factory);}else{factory(root);}}(this,function(exports){var VERSION='0.4.0';function WideArea(obj){this._targetElement=obj;this._wideAreaId=1;this._options={wideAreaAttr:'data-widearea',exitOnEsc:true,defaultColorScheme:'light',closeIconLabel:'Close WideArea',changeThemeIconLabel:'Toggle Color Scheme',fullScreenIconLabel:'WideArea Mode',autoSaveKeyPrefix:'WDATA-'};_enable.call(this);}
function _saveToStorage(id,value){localStorage.setItem(this._options.autoSaveKeyPrefix+id,value);}
function _getFromStorage(id){return localStorage.getItem(this._options.autoSaveKeyPrefix+id);}
function _clearStorage(value){var currentElement,id;if(typeof(value)=="string"){currentElement=this._targetElement.querySelector(value);if(currentElement){id=parseInt(currentElement.getAttribute("data-widearea-id"));}}else if(typeof(value)=="number"){currentElement=this._targetElement.querySelector('textarea[data-widearea-id="'+value+'"]');id=value;}else if(typeof(value)=="object"){currentElement=value;if(currentElement){id=parseInt(currentElement.getAttribute("data-widearea-id"));}}
if(currentElement&&id){currentElement.value='';localStorage.removeItem(this._options.autoSaveKeyPrefix+id);}}
function _enable(){var self=this,textAreaList=this._targetElement.querySelectorAll('textarea['+this._options.wideAreaAttr+'=\'enable\']'),fullscreenIconClickHandler=function(){_enableFullScreen.call(self,this);};this._textareas=[];for(var i=textAreaList.length-1;i>=0;i--){var currentTextArea=textAreaList[i];var wideAreaWrapper=document.createElement('div'),wideAreaIcons=document.createElement('div'),fullscreenIcon=document.createElement('a');wideAreaWrapper.className='widearea-wrapper';wideAreaIcons.className='widearea-icons';fullscreenIcon.className='widearea-icon fullscreen';fullscreenIcon.title=this._options.fullScreenIconLabel;fullscreenIcon.href='javascript:void(0);';fullscreenIcon.draggable=false;fullscreenIcon.onclick=fullscreenIconClickHandler;currentTextArea.className=(currentTextArea.className+" widearea").replace(/^\s+|\s+$/g,"");currentTextArea.setAttribute("data-widearea-id",this._wideAreaId);wideAreaIcons.setAttribute("id","widearea-"+this._wideAreaId);if(_getFromStorage.call(this,this._wideAreaId)){currentTextArea.value=_getFromStorage.call(this,this._wideAreaId);}
var onTextChanged=function(){_saveToStorage.call(self,this.getAttribute('data-widearea-id'),this.value);};if(currentTextArea.addEventListener){currentTextArea.addEventListener('input',onTextChanged,false);}else if(currentTextArea.attachEvent){currentTextArea.attachEvent('onpropertychange',onTextChanged);}
++this._wideAreaId;currentTextArea.parentNode.insertBefore(wideAreaWrapper,currentTextArea);wideAreaWrapper.appendChild(currentTextArea);wideAreaIcons.appendChild(fullscreenIcon);wideAreaWrapper.appendChild(wideAreaIcons);this._textareas.push(currentTextArea);}}
function _enableFullScreen(link){var self=this;var wideAreaId=parseInt(link.parentNode.id.replace(/widearea\-/,""));var targetTextarea=document.querySelector("textarea[data-widearea-id='"+wideAreaId+"']");var currentTextArea=targetTextarea.cloneNode();currentTextArea.className=('widearea-fullscreen '+targetTextarea.className).replace(/^\s+|\s+$/g,"");targetTextarea.className=('widearea-fullscreened '+targetTextarea.className).replace(/^\s+|\s+$/g,"");var controlPanel=document.createElement('div');controlPanel.className='widearea-controlPanel';var closeIcon=document.createElement('a');closeIcon.href='javascript:void(0);';closeIcon.className='widearea-icon close';closeIcon.title=this._options.closeIconLabel;closeIcon.onclick=function(){_disableFullScreen.call(self);};closeIcon.draggable=false;var changeThemeIcon=document.createElement('a');changeThemeIcon.href='javascript:void(0);';changeThemeIcon.className='widearea-icon changeTheme';changeThemeIcon.title=this._options.changeThemeIconLabel;changeThemeIcon.onclick=function(){_toggleColorScheme.call(self);};changeThemeIcon.draggable=false;controlPanel.appendChild(closeIcon);controlPanel.appendChild(changeThemeIcon);var overlayLayer=document.createElement('div');overlayLayer.className='widearea-overlayLayer '+this._options.defaultColorScheme;var markdown=document.createElement('div');markdown.className='markdown';overlayLayer.appendChild(currentTextArea);overlayLayer.appendChild(controlPanel);overlayLayer.appendChild(markdown);jQuery(currentTextArea).afterselect(function(){var totaltip=jQuery('.totaltip').hide();totaltip.first().css({top:stacks.totalMousePos.y+15,left:stacks.totalMousePos.x-15}).fadeIn('fast');jQuery("textarea,input").one("mousedown keydown scroll",function(){totaltip.removeAttr('style');});jQuery(document).one("scroll",function(event){totaltip.removeAttr('style');});});document.body.appendChild(overlayLayer);currentTextArea.focus();currentTextArea.value=targetTextarea.value;jQuery(currentTextArea).markdown({target_form:".markdown"});jQuery("body>.totalbar").hide().addClass("fullscreen").fadeIn();var onTextChanged=function(){_saveToStorage.call(self,this.getAttribute('data-widearea-id'),this.value);$(currentTextArea).markdown({target_form:".markdown"});};if(currentTextArea.addEventListener){currentTextArea.addEventListener('input',onTextChanged,false);}else if(currentTextArea.attachEvent){currentTextArea.attachEvent('onpropertychange',onTextChanged);}
jQuery('.totalbar .button,#totaltip').click(function(){$(currentTextArea).delay(200).markdown({target_form:".markdown"});});this._onKeyDown=function(e){if(e.keyCode===27&&self._options.exitOnEsc){_disableFullScreen.call(self);}
if(e.keyCode==9){e.preventDefault();var selectionStart=currentTextArea.selectionStart;currentTextArea.value=currentTextArea.value.substring(0,selectionStart)+"\t"+currentTextArea.value.substring(currentTextArea.selectionEnd);currentTextArea.selectionEnd=selectionStart+1;}};if(window.addEventListener){window.addEventListener('keydown',self._onKeyDown,true);}else if(document.attachEvent){document.attachEvent('onkeydown',self._onKeyDown);}}
function _toggleColorScheme(){var overlayLayer=document.querySelector(".widearea-overlayLayer");if(/dark/gi.test(overlayLayer.className)){overlayLayer.className=overlayLayer.className.replace('dark','light');}else{overlayLayer.className=overlayLayer.className.replace('light','dark');}
jQuery("body>.totalbar.fullscreen").toggleClass("dark");}
function _disableFullScreen(){var smallTextArea=document.querySelector("textarea.widearea-fullscreened");var overlayLayer=document.querySelector(".widearea-overlayLayer");var fullscreenTextArea=overlayLayer.querySelector("textarea");jQuery("body>.totalbar").removeClass("fullscreen").hide();smallTextArea.focus();smallTextArea.value=fullscreenTextArea.value;smallTextArea.className=smallTextArea.className.replace(/widearea-fullscreened/gi,"").replace(/^\s+|\s+$/g,"");overlayLayer.parentNode.removeChild(overlayLayer);if(window.removeEventListener){window.removeEventListener('keydown',this._onKeyDown,true);}else if(document.detachEvent){document.detachEvent('onkeydown',this._onKeyDown);}}
function _mergeOptions(obj1,obj2){var obj3={},attrname;for(attrname in obj1){obj3[attrname]=obj1[attrname];}
for(attrname in obj2){obj3[attrname]=obj2[attrname];}
return obj3;}
var wideArea=function(selector){if(typeof(selector)==='string'){var targetElement=document.querySelector(selector);if(targetElement){return new WideArea(targetElement);}else{throw new Error('There is no element with given selector.');}}else{return new WideArea(document.body);}};wideArea.version=VERSION;wideArea.fn=WideArea.prototype={clone:function(){return new WideArea(this);},setOption:function(option,value){this._options[option]=value;return this;},setOptions:function(options){this._options=_mergeOptions(this._options,options);return this;},clearData:function(value){_clearStorage.call(this,value);return this;}};exports.wideArea=wideArea;return wideArea;}));
