
function photoAlbumLightCase(){$('.thumbnail-frame a').each(function(){var theDescription=$(this).next('p').html();var htmlURL=$(this).attr('href');var imageURL=htmlURL.replace(/html/,'jpg');$(this).attr('href',imageURL);$(this).attr('data-rel','lightcase:PhotoAlbum');$(this).attr('title',theDescription);$(this).lightcase({transition:'scrollHorizontal',showSequenceInfo:true,showTitle:true,labels:{'sequenceInfo.of':' / ',},maxHeight:1600,maxWidth:2400});});}
function setUpLightcase(){$('a.lightcase').lightcase({maxWidth:2400,maxHeight:1600,iframe:{width:'90%',height:'90%',frameborder:0}});}
function kubeStyles(){$('input[type=submit], input[type=reset], input[type=button]').addClass('btn');}
function setUpShareIcons(){$('.navButton').after('<div id="shareIcons"></div>');$('#shareIcons').append($('<ul class="contact"></ul>'));$('ul.contact').append($('a.facebook')).append($('a.twitter')).append($('a.googleplus')).append($('a.linkedin')).append($('a.youtube')).append($('a.flickr')).append($('a.dribbble')).append($('a.skype')).append($('a.tumblr')).append($('a.foursquare')).append($('a.instagram')).append($('a.pinterest')).append($('a.email')).append($('a.soundcloud')).append($('a.reddit')).append($('a.blogger')).append($('a.evernote')).append($('a.delicious')).append($('a.lastfm')).append($('a.picasa')).append($('a.vimeo')).append($('a.yelp')).append($('a.rss'));$('a.facebook').wrap('<li></li>');$('a.facebook').html('<i class="fa fa-facebook"></i>');$('a.twitter').wrap('<li></li>');$('a.twitter').html('<i class="fa fa-twitter"></i>');$('a.rss').wrap('<li></li>');$('a.rss').html('<i class="fa fa-rss"></i>');$('a.googleplus').wrap('<li></li>');$('a.googleplus').html('<i class="fa fa-google-plus"></i>');$('a.linkedin').wrap('<li></li>');$('a.linkedin').html('<i class="fa fa-linkedin"></i>');$('a.dribbble').wrap('<li></li>');$('a.dribbble').html('<i class="fa fa-dribbble"></i>');$('a.youtube').wrap('<li></li>');$('a.youtube').html('<i class="fa fa-youtube"></i>');$('a.flickr').wrap('<li></li>');$('a.flickr').html('<i class="fa fa-flickr"></i>');$('a.skype').wrap('<li></li>');$('a.skype').html('<i class="fa fa-skype"></i>');$('a.tumblr').wrap('<li></li>');$('a.tumblr').html('<i class="fa fa-tumblr"></i>');$('a.foursquare').wrap('<li></li>');$('a.foursquare').html('<i class="fa fa-foursquare"></i>');$('a.instagram').wrap('<li></li>');$('a.instagram').html('<i class="fa fa-instagram"></i>');$('a.pinterest').wrap('<li></li>');$('a.pinterest').html('<i class="fa fa-pinterest"></i>');$('a.email').wrap('<li></li>');$('a.email').html('<i class="fa fa-envelope"></i>');$('a.soundcloud').wrap('<li></li>');$('a.soundcloud').html('<i class="fa fa-soundcloud"></i>');$('a.reddit').wrap('<li></li>');$('a.reddit').html('<i class="fa fa-reddit"></i>');$('a.delicious').wrap('<li></li>');$('a.delicious').html('<i class="fa fa-delicious"></i>');$('a.lastfm').wrap('<li></li>');$('a.lastfm').html('<i class="fa fa-lastfm"></i>');$('a.vimeo').wrap('<li></li>');$('a.vimeo').html('<i class="fa fa-vimeo"></i>');$('a.yelp').wrap('<li></li>');$('a.yelp').html('<i class="fa fa-yelp"></i>');}
function fadeConentIn(){$('body').fadeTo(1000,1);}
function fadeContentOut(){$('#navWrapper a').each(function(){var newPage=this.href;var relAttribute=this.rel;var pageName=newPage.substring(newPage.lastIndexOf('/')+1);jQuery(this).on('click',function(ev){ev.preventDefault();jQuery('body').fadeOut(1000,function(){document.location.href=newPage;});});});}
function link2AudiojQuery(){$('a[href$=".mp3"],a[href$=".aac"],a[href$=".ogg"],a[href$=".wav"]').not('a[rel]').each(function(index){var audioURL=jQuery(this).attr('href');var audioElement=document.createElement('audio');audioElement.src=audioURL;audioElement.style.maxWidth='100%';audioElement.controls='controls';jQuery(this).after(audioElement);jQuery(this).remove();});}
function link2VideojQuery(){$('a[href$=".mp4"],a[href$=".ogv"],a[href$=".webm"]').not('a[rel]').each(function(index){var videoURL=jQuery(this).attr('href');var videoElement=document.createElement('video');videoElement.src=videoURL;videoElement.style.maxWidth='100%';videoElement.controls='controls';jQuery(this).after(videoElement);jQuery(this).remove();});}
function mediaElementStart(){$('video,audio').mediaelementplayer({success:function(){}});}
$(document).ready(function(){$('.navButton').on('click',function(){var theNavLink=$(this).find('.c-hamburger');if(theNavLink.hasClass('is-active')){$('#navWrapper').fadeOut();}
else{$('#navWrapper').css({'visibility':'visible','display':'none'});$('#navWrapper').fadeIn();}
theNavLink.toggleClass('is-active');});$('#navWrapper nav a').on('click',function(e){e.preventDefault();})
$('.main').find('h1:first').css('margin-top','0');$('.sidebar').find('h1:first').css('margin-top','0');setUpShareIcons();photoAlbumLightCase();setUpLightcase();kubeStyles();$
fadeConentIn();fadeContentOut();if(typeof MEEnable!=="undefined"){link2AudiojQuery();link2VideojQuery();mediaElementStart();}});$(window).on('load',function(){if($('link[href*="consolidated"]').length){$('.mejs-controls .mejs-button button').css({'background-image':'url('+theMEPath[1]+')','background-color':'transparent'});$('.no-svg .mejs-overlay-button, .mejs-overlay-button').css('background-image','url('+theMEPath[0]+')');}
else{}});$(window).bind("pageshow",function(event){if(event.originalEvent.persisted){window.location.reload();}});